### ISSUE TITLE
New instrument connection not possible 

### ISSUE THREAD

**Issue by fiscnil** [Rohde-Schwarz/RcIcPluginBugTracking#2]
After updating to PyCharm 2022.3.2 (Community Edition) Build #PC-223.8617.48, I can't connect to new instruments any more. Ping is still working, but not test. I tried this with FSW and SMA. Following error is displayed by SCPI Logger: 
_Opening test ERROR: Could not initialize class com.sun.jna.NativeLong_
R&S Instruments Plugin Version: 1.2.0

**Comment by Miloslav-RS** [comment]
Please update to RsIC 1.3.1, this should work OK.
