### ISSUE TITLE
SCPI recorder Button grayed out, can not click

### ISSUE THREAD

**Issue by Blue-FatMan** [Rohde-Schwarz/RcIcPluginBugTracking#4]
SCPI recorder Button grayed out, in  CMW500, my device can connect, but can not use SCPI recorder, it had grayed out

the version pycharm and plugin all of newlatest

![img_v2_9cf89428-6b47-4c45-9e44-624140bfd98g](https://github.com/Rohde-Schwarz/RcIcPluginBugTracking/assets/22763910/36df6e9b-2c14-4f2c-8106-0d9525f43b60)

**Comment by Miloslav-RS** [comment]
Unfortunately, not every instrument in our portfolio is capable of SCPI Recording. The CMW is one of them. Sorry about that :-(
We will improve the hover-over tool tip to show a reason for why some tabs are disabled.
